# Jekyll configuration for CV site
markdown: kramdown
style: modern

# Build settings
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

# Exclude files
exclude:
  - README.md
  - README_UPDATE.md
  - Gemfile
  - Gemfile.lock
  - vendor
